<?xml version="1.0" encoding="UTF-8"?>
<!-- Data generated by EDINA Digimap, University of Edinburgh for sot:3fe2a459324b394b on Fri Apr 15 15:40:02 BST 2011. -->
<!--Created by GO Publisher WFS 1.4.3 Build 18958 from 2010-03-09 15:17--><!--Snowflake Software Ltd. (http://www.snowflakesoftware.co.uk)--><osgb:FeatureCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:osgb="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.ordnancesurvey.co.uk/xml/namespaces/osgb http://www.ordnancesurvey.co.uk/xml/schema/v6/OSDNFFeatures.xsd">
<gml:boundedBy>
<gml:null>unknown</gml:null>
</gml:boundedBy>
<osgb:queryTime>2011-04-15T15:40:02</osgb:queryTime>
<osgb:cartographicMember>
<osgb:CartographicText fid="osgb1000001329134498">
<osgb:featureCode>10026</osgb:featureCode>
<osgb:version>1</osgb:version>
<osgb:versionDate>2001-11-06</osgb:versionDate>
<osgb:theme>Buildings</osgb:theme>
<osgb:anchorPoint>
<gml:Point srsName="osgb:BNG">
<gml:coordinates>440040.05,115122.25</gml:coordinates>
</gml:Point>
</osgb:anchorPoint>
<osgb:changeHistory>
<osgb:changeDate>1985-08-02</osgb:changeDate>
<osgb:reasonForChange>New</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:descriptiveGroup>Buildings Or Structure</osgb:descriptiveGroup>
<osgb:make>Manmade</osgb:make>
<osgb:physicalLevel>50</osgb:physicalLevel>
<osgb:textRendering>
<osgb:anchorPosition>7</osgb:anchorPosition>
<osgb:font>1</osgb:font>
<osgb:height>1.75</osgb:height>
<osgb:orientation>0</osgb:orientation>
</osgb:textRendering>
<osgb:textString>The Lodge</osgb:textString>
</osgb:CartographicText>
</osgb:cartographicMember>
<osgb:topographicMember>
<osgb:TopographicArea fid="osgb1000016425341">
<osgb:featureCode>10021</osgb:featureCode>
<osgb:version>3</osgb:version>
<osgb:versionDate>2006-09-15</osgb:versionDate>
<osgb:theme>Buildings</osgb:theme>
<osgb:calculatedAreaValue>85.7214</osgb:calculatedAreaValue>
<osgb:changeHistory>
<osgb:changeDate>2006-07-18</osgb:changeDate>
<osgb:reasonForChange>Attributes</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:changeHistory>
<osgb:changeDate>1985-08-02</osgb:changeDate>
<osgb:reasonForChange>New</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:descriptiveGroup>Building</osgb:descriptiveGroup>
<osgb:make>Manmade</osgb:make>
<osgb:physicalLevel>50</osgb:physicalLevel>
<osgb:polygon>
<gml:Polygon srsName="osgb:BNG">
<gml:outerBoundaryIs>
<gml:LinearRing>
<gml:coordinates>440047.03,115122.18 440048.05,115122.6 440048.2,115122.22 440048.31,115121.95 440052.55,115123.7 440048.4,115133.95 440048.24,115133.88 440046.55,115133.15 440047.6,115130.6 440045.25,115129.65 440045.5,115129.0 440039.75,115126.65 440042.4,115120.3 440047.03,115122.18</gml:coordinates>
</gml:LinearRing>
</gml:outerBoundaryIs>
</gml:Polygon>
</osgb:polygon>
</osgb:TopographicArea>
</osgb:topographicMember>
<osgb:topographicMember>
<osgb:TopographicLine fid="osgb1000000156979491">
<osgb:featureCode>10019</osgb:featureCode>
<osgb:version>2</osgb:version>
<osgb:versionDate>2006-09-15</osgb:versionDate>
<osgb:theme>Buildings</osgb:theme>
<osgb:theme>Land</osgb:theme>
<osgb:accuracyOfPosition>1.0m</osgb:accuracyOfPosition>
<osgb:changeHistory>
<osgb:changeDate>1985-08-02</osgb:changeDate>
<osgb:reasonForChange>New</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:changeHistory>
<osgb:changeDate>2006-07-18</osgb:changeDate>
<osgb:reasonForChange>Attributes</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:descriptiveGroup>Building</osgb:descriptiveGroup>
<osgb:descriptiveTerm>Outline</osgb:descriptiveTerm>
<osgb:make>Manmade</osgb:make>
<osgb:physicalLevel>50</osgb:physicalLevel>
<osgb:physicalPresence>Obstructing</osgb:physicalPresence>
<osgb:polyline>
<gml:LineString srsName="osgb:BNG">
<gml:coordinates>440047.03,115122.18 440042.4,115120.3</gml:coordinates>
</gml:LineString>
</osgb:polyline>
</osgb:TopographicLine>
</osgb:topographicMember>
<osgb:topographicMember>
<osgb:TopographicLine fid="osgb1000000156980001">
<osgb:featureCode>10019</osgb:featureCode>
<osgb:version>2</osgb:version>
<osgb:versionDate>2006-09-15</osgb:versionDate>
<osgb:theme>Buildings</osgb:theme>
<osgb:theme>Land</osgb:theme>
<osgb:accuracyOfPosition>1.0m</osgb:accuracyOfPosition>
<osgb:changeHistory>
<osgb:changeDate>1985-08-02</osgb:changeDate>
<osgb:reasonForChange>New</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:changeHistory>
<osgb:changeDate>2006-07-01</osgb:changeDate>
<osgb:reasonForChange>Restructured</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:descriptiveGroup>Building</osgb:descriptiveGroup>
<osgb:descriptiveTerm>Outline</osgb:descriptiveTerm>
<osgb:make>Manmade</osgb:make>
<osgb:physicalLevel>50</osgb:physicalLevel>
<osgb:physicalPresence>Obstructing</osgb:physicalPresence>
<osgb:polyline>
<gml:LineString srsName="osgb:BNG">
<gml:coordinates>440042.4,115120.3 440039.75,115126.65 440045.5,115129.0 440045.25,115129.65 440047.6,115130.6 440046.55,115133.15 440048.24,115133.88</gml:coordinates>
</gml:LineString>
</osgb:polyline>
</osgb:TopographicLine>
</osgb:topographicMember>
<osgb:topographicMember>
<osgb:TopographicLine fid="osgb1000000156980218">
<osgb:featureCode>10019</osgb:featureCode>
<osgb:version>2</osgb:version>
<osgb:versionDate>2006-09-15</osgb:versionDate>
<osgb:theme>Buildings</osgb:theme>
<osgb:theme>Roads Tracks And Paths</osgb:theme>
<osgb:accuracyOfPosition>1.0m</osgb:accuracyOfPosition>
<osgb:changeHistory>
<osgb:changeDate>1985-08-02</osgb:changeDate>
<osgb:reasonForChange>New</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:changeHistory>
<osgb:changeDate>2006-07-18</osgb:changeDate>
<osgb:reasonForChange>Attributes</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:descriptiveGroup>Building</osgb:descriptiveGroup>
<osgb:descriptiveTerm>Outline</osgb:descriptiveTerm>
<osgb:make>Manmade</osgb:make>
<osgb:physicalLevel>50</osgb:physicalLevel>
<osgb:physicalPresence>Obstructing</osgb:physicalPresence>
<osgb:polyline>
<gml:LineString srsName="osgb:BNG">
<gml:coordinates>440048.31,115121.95 440048.2,115122.22 440048.05,115122.6 440047.03,115122.18</gml:coordinates>
</gml:LineString>
</osgb:polyline>
</osgb:TopographicLine>
</osgb:topographicMember>
<osgb:topographicMember>
<osgb:TopographicLine fid="osgb1000000156980479">
<osgb:featureCode>10019</osgb:featureCode>
<osgb:version>2</osgb:version>
<osgb:versionDate>2006-09-15</osgb:versionDate>
<osgb:theme>Buildings</osgb:theme>
<osgb:theme>Land</osgb:theme>
<osgb:accuracyOfPosition>1.0m</osgb:accuracyOfPosition>
<osgb:changeHistory>
<osgb:changeDate>1985-08-02</osgb:changeDate>
<osgb:reasonForChange>New</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:changeHistory>
<osgb:changeDate>2006-07-18</osgb:changeDate>
<osgb:reasonForChange>Attributes</osgb:reasonForChange>
</osgb:changeHistory>
<osgb:descriptiveGroup>Building</osgb:descriptiveGroup>
<osgb:descriptiveTerm>Outline</osgb:descriptiveTerm>
<osgb:make>Manmade</osgb:make>
<osgb:physicalLevel>50</osgb:physicalLevel>
<osgb:physicalPresence>Obstructing</osgb:physicalPresence>
<osgb:polyline>
<gml:LineString srsName="osgb:BNG">
<gml:coordinates>440048.24,115133.88 440048.4,115133.95 440052.55,115123.7 440048.31,115121.95</gml:coordinates>
</gml:LineString>
</osgb:polyline>
</osgb:TopographicLine>
</osgb:topographicMember>
</osgb:FeatureCollection>
